name: Docker Build

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - "server.py"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build Docker image
        run: |
          docker build -t brain-trust:ci .
